In [1]:
!git pull

Already up-to-date.


In [2]:
import sys, os
sys.path.append('/root/DVA/server/')
import dvalib
import faiss
import numpy as np
from dvalib import approximator
from dvalib import retriever
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dva.settings")
django.setup()
from dvaapp import models

Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.


In [4]:
di = models.IndexEntries.objects.get(approximator_shasum="dd808786881c0f6226a66a84cce9ee9c957dbe79")
mat, entries = di.load_index()
print mat

/root/media//22902add-9822-4751-8265-3c587abe19d4/indexes/5ff6394a_66df_11e8_9235_0242ac120005.index


In [8]:
index = faiss.read_index(str(mat).replace('//','/'),faiss.IO_FLAG_MMAP)

In [13]:
other_index = faiss.read_index(a.index_path)

In [15]:
other_index.index.merge_from(index,other_index.ntotal)

AttributeError: merge_from

In [12]:
index.invlists

AttributeError: invlists

In [5]:
from dvaapp.operations import approximation

In [6]:
a, da = approximation.Approximators.get_approximator_by_shasum("dd808786881c0f6226a66a84cce9ee9c957dbe79")

In [ ]:
r = retriever.FaissApproximateRetriever(name="adsasd",)

In [ ]:
a = approximator.FAISSApproximator("a","a","PCA64;Flat",128,trainable=False)
r = retriever.FaissRetriever(name="faiss_1",approximator=a)

In [12]:
a = approximator.FAISSApproximator("a","a","PCA64;Flat",128,trainable=False)
r = retriever.FaissRetriever(name="faiss_1",approximator=a)

In [19]:
for k in range(mat.shape[0]):
    distances, ids = r.fass_index.search(np.atleast_2d(mat[k,:,:]),3)
    print ids[0]

[0 1 2]
[1 0 2]
[2 1 0]
[3 2 1]
[4 7 2]
[5 4 6]
[6 8 2]
[7 4 8]
[8 6 7]
