In [1]:
!git pull

Already up-to-date.


In [2]:
import sys, os
sys.path.append('/root/DVA/server/')
import dvalib
import faiss
import numpy as np
from dvalib import approximator
from dvalib import retriever
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dva.settings")
django.setup()
from dvaapp import models

Failed to load GPU Faiss: No module named swigfaiss_gpu
Faiss falling back to CPU-only.


In [11]:
di = models.IndexEntries.objects.latest('created')
mat, entries = di.load_index()
print mat.shape

(9, 1, 128)


In [12]:
a = approximator.FAISSApproximator("a","a","PCA64;Flat",128,trainable=False)
r = retriever.FaissRetriever(name="faiss_1",approximator=a)

In [19]:
for k in range(mat.shape[0]):
    distances, ids = r.fass_index.search(np.atleast_2d(mat[k,:,:]),3)
    print ids[0]

[0 1 2]
[1 0 2]
[2 1 0]
[3 2 1]
[4 7 2]
[5 4 6]
[6 8 2]
[7 4 8]
[8 6 7]
